---
- name: Install Kubernetes v1.30 on k8s-master
  hosts: k8s-master
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install packages needed for Kubernetes apt repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg
        state: present

    - name: Create /etc/apt/keyrings directory if it doesn't exist
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes signing key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'

    - name: Add Kubernetes apt repository
      lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
        create: yes

    - name: Update apt package index again
      apt:
        update_cache: yes

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
        force_apt_get: yes
        allow_change_held_packages: yes

    - name: Pin kubelet, kubeadm, and kubectl versions
      apt:
        pkg:
          - kubelet
          - kubeadm
          - kubectl
        state: hold

    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: yes
        state: started
...
